### ISSUE TITLE
Client Routing not working 

### ISSUE THREAD

**Issue by ParishKhan** [remarkablemark/universal-react-tutorial#2]
on **upgrade-react-router** example, client-side routing not working.

**Comment by remarkablemark** [comment]
Thanks for letting me know @ParishKhan 

I fixed it by updating `package.json` and saving all dependencies to its exact version. The error was coming from `react-router@4.1` being installed instead of `react-router@4.0`.

Feel free to pull and install to get the app working again.

**Comment by ParishKhan** [comment]
Client-side routing still not working. It's only updating the URL not the component.
